version: 1.0.{build}
branches:
  only:
  - master
only_commits:
  files:
    - appveyor.yml
    - script/*.ps1
image: Visual Studio 2017
clone_folder: c:\propositum
#init:
#- ps: $blockRdp = $true
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  supersetpassword:
    secure: 6ldsCuuJVKGYr44vbdnjSw==
  githubapitoken:
    secure: nST1cukl1Jl5NpnP53P7y2SOFs4dYTbhVFu9r8vBL/c/xSsUVHRxhMJqpou4qUtQ
  propositumDrv: 'P:'
  bintrayDeploy: true
  githubDeploy: false
build_script:
- ps: . ./script/propositum-windows.ps1
test: off
artifacts:
- path: propositum.zip
  name: propositum-zip
deploy:
- ps: $blockRdp = $true
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- provider: BinTray
  username: xeijin
  api_key:
    secure: O0DhLTtmK77asEUTQzGE+6rO0ANBZEA1AUnH9rR4FpwgIUBwSE7Eh4L0dUJexsU9
  subject: xeijin
  repo: propositum
  package: propositum
  artifact: propositum-zip
  explode: true
  on:
    bintrayDeploy: true
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: propositum
  template: <{{buildUrl}}|⚙️ → ✅ Build Success {{buildVersion}} {{status}}>
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: propositum
  template: <{{buildUrl}}|⚙️ → ❌ Build Failed {{buildVersion}} {{status}}>
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
  
